name: mono_melos
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  melos: '2.9.0'
  header_module:
    git:
      url: https://github.com/oleksandr-pluzhnyk-dp/melos-multiverse-modules.git
      path: mono_melos/packages/header_module
      ref: header_module-v0.0.6 # can be branch, tag or git hash

  http_utility:
    git:
      url: https://github.com/oleksandr-pluzhnyk-dp/melos-multiverse-modules.git
      path: mono_melos/packages/http_utility
      ref: http_utility.0.0.1 # can be branch, tag or git hash

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  http_utility:
    git:
      url: https://github.com/oleksandr-pluzhnyk-dp/melos-multiverse-modules.git
      path: mono_melos/packages/http_utility
      ref: http_utility.0.0.2 # can be branch, tag or git hash

flutter:
  uses-material-design: true
